import type { CyberFeed, InterpolAggregate, RestCountryRecord } from "@/types/risk";

import { normalizeCountries, normalizeOutbreakDisease } from "./normalizers";

const fallbackCountriesRaw: RestCountryRecord[] = [
  {
    name: { common: "United States", official: "United States of America" },
    cca2: "US",
    cca3: "USA",
    ccn3: "840",
    population: 334_805_269,
    area: 9_833_517,
    borders: ["CAN", "MEX"],
    flags: { svg: "https://flagcdn.com/us.svg" },
    latlng: [38, -97],
    region: "Americas",
  },
  {
    name: { common: "India", official: "Republic of India" },
    cca2: "IN",
    cca3: "IND",
    ccn3: "356",
    population: 1_400_000_000,
    area: 3_287_263,
    borders: ["PAK", "CHN", "NPL", "BGD", "BTN", "MMR"],
    flags: { svg: "https://flagcdn.com/in.svg" },
    latlng: [20, 77],
    region: "Asia",
  },
  {
    name: { common: "China", official: "People's Republic of China" },
    cca2: "CN",
    cca3: "CHN",
    ccn3: "156",
    population: 1_412_600_000,
    area: 9_706_961,
    borders: ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "NPL", "PAK", "RUS", "TJK", "VNM"],
    flags: { svg: "https://flagcdn.com/cn.svg" },
    latlng: [35, 105],
    region: "Asia",
  },
  {
    name: { common: "Brazil", official: "Federative Republic of Brazil" },
    cca2: "BR",
    cca3: "BRA",
    ccn3: "076",
    population: 214_326_223,
    area: 8_515_767,
    borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
    flags: { svg: "https://flagcdn.com/br.svg" },
    latlng: [-10, -55],
    region: "Americas",
  },
  {
    name: { common: "Russia", official: "Russian Federation" },
    cca2: "RU",
    cca3: "RUS",
    ccn3: "643",
    population: 144_100_000,
    area: 17_098_242,
    borders: ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
    flags: { svg: "https://flagcdn.com/ru.svg" },
    latlng: [60, 100],
    region: "Europe",
  },
  {
    name: { common: "Nigeria", official: "Federal Republic of Nigeria" },
    cca2: "NG",
    cca3: "NGA",
    ccn3: "566",
    population: 213_401_323,
    area: 923_768,
    borders: ["BEN", "CMR", "TCD", "NER"],
    flags: { svg: "https://flagcdn.com/ng.svg" },
    latlng: [10, 8],
    region: "Africa",
  },
  {
    name: { common: "France", official: "French Republic" },
    cca2: "FR",
    cca3: "FRA",
    ccn3: "250",
    population: 67_749_632,
    area: 551_695,
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
    flags: { svg: "https://flagcdn.com/fr.svg" },
    latlng: [46, 2],
    region: "Europe",
  },
  {
    name: { common: "Australia", official: "Commonwealth of Australia" },
    cca2: "AU",
    cca3: "AUS",
    ccn3: "036",
    population: 25_890_773,
    area: 7_692_024,
    borders: [],
    flags: { svg: "https://flagcdn.com/au.svg" },
    latlng: [-27, 133],
    region: "Oceania",
  },
  {
    name: { common: "South Africa", official: "Republic of South Africa" },
    cca2: "ZA",
    cca3: "ZAF",
    ccn3: "710",
    population: 59_392_255,
    area: 1_221_037,
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
    flags: { svg: "https://flagcdn.com/za.svg" },
    latlng: [-29, 24],
    region: "Africa",
  },
  {
    name: { common: "DR Congo", official: "Democratic Republic of the Congo" },
    cca2: "CD",
    cca3: "COD",
    ccn3: "180",
    population: 108_407_721,
    area: 2_344_858,
    borders: ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"],
    flags: { svg: "https://flagcdn.com/cd.svg" },
    latlng: [0, 25],
    region: "Africa",
  },
  {
    name: { common: "Uganda", official: "Republic of Uganda" },
    cca2: "UG",
    cca3: "UGA",
    ccn3: "800",
    population: 45_853_778,
    area: 241_550,
    borders: ["COD", "KEN", "RWA", "SSD", "TZA"],
    flags: { svg: "https://flagcdn.com/ug.svg" },
    latlng: [1, 32],
    region: "Africa",
  },
  {
    name: { common: "Bangladesh", official: "People's Republic of Bangladesh" },
    cca2: "BD",
    cca3: "BGD",
    ccn3: "050",
    population: 169_356_251,
    area: 147_570,
    borders: ["IND", "MMR"],
    flags: { svg: "https://flagcdn.com/bd.svg" },
    latlng: [24, 90],
    region: "Asia",
  },
];

export const fallbackCountries = normalizeCountries(fallbackCountriesRaw);

export const fallbackDisease = normalizeOutbreakDisease(
  [
    {
      DonId: "fallback-don-1",
      Title: "Ebola disease caused by Bundibugyo virus, Democratic Republic of the Congo & Uganda",
      PublicationDateAndTime: new Date().toISOString(),
      UrlName: "2026-DON602",
    },
    {
      DonId: "fallback-don-2",
      Title: "Measles - Bangladesh",
      PublicationDateAndTime: new Date(Date.now() - 86_400_000).toISOString(),
      UrlName: "2026-DON598",
    },
  ],
  [
    {
      title: "Dengue outbreak reports continue across India",
      sourcecountry: "India",
      seendate: new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""),
      url: "https://www.who.int/emergencies/disease-outbreak-news",
      domain: "who.int",
    },
    {
      title: "Cholera outbreak response expands in Nigeria",
      sourcecountry: "Nigeria",
      seendate: new Date(Date.now() - 2 * 86_400_000).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""),
      url: "https://www.who.int/emergencies/disease-outbreak-news",
      domain: "who.int",
    },
  ],
  fallbackCountries,
);

export const fallbackInterpol: InterpolAggregate = {
  counts: {
    USA: 9,
    IND: 14,
    CHN: 8,
    BRA: 11,
    RUS: 10,
    FRA: 7,
    NGA: 13,
    ZAF: 6,
  },
  notices: [
    { id: "fallback-interpol-1", name: "CLASSIFIED SUBJECT A", nationalities: ["IN"], charges: "Fraud and organized crime" },
    { id: "fallback-interpol-2", name: "CLASSIFIED SUBJECT B", nationalities: ["NG"], charges: "Cyber-enabled financial crime" },
    { id: "fallback-interpol-3", name: "CLASSIFIED SUBJECT C", nationalities: ["BR"], charges: "Drug trafficking" },
    { id: "fallback-interpol-4", name: "CLASSIFIED SUBJECT D", nationalities: ["US"], charges: "Violent crime" },
  ],
  total: 78,
  source: "fallback",
  fetchedAt: new Date().toISOString(),
  error: "Interpol upstream blocked this runtime; showing seeded aggregate fallback.",
};

export const fallbackCyber: CyberFeed = {
  counts: {
    USA: 4,
    FRA: 2,
    IND: 3,
    RUS: 2,
  },
  incidents: [
    {
      kind: "CYBER",
      id: "fallback-cyber-1",
      title: "Ransomware activity reported against healthcare systems",
      country: "United States",
      countryCode: "USA",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
    {
      kind: "CYBER",
      id: "fallback-cyber-2",
      title: "DDoS disruption reported against telecom infrastructure",
      country: "France",
      countryCode: "FRA",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
    {
      kind: "CYBER",
      id: "fallback-cyber-3",
      title: "Data breach coverage detected across regional outlets",
      country: "India",
      countryCode: "IND",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
  ],
  vulnerabilities: [
    {
      kind: "CISA KEV",
      id: "CVE-FALLBACK-1",
      cve: "CVE-FALLBACK-1",
      vendor: "Multiple vendors",
      product: "Internet-facing systems",
      name: "Known exploited vulnerability catalog fallback",
      dateAdded: new Date().toISOString().slice(0, 10),
      ransomware: "Unknown",
      action: "Review CISA KEV guidance and prioritize remediation.",
      url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    },
  ],
  total: 11,
  source: "fallback",
  fetchedAt: new Date().toISOString(),
  cisaCatalogVersion: "fallback",
  error: "Cyber upstream unavailable; showing seeded incident fallback.",
};
