import type { CyberFeed, InterpolAggregate, RestCountryRecord } from "@/types/risk";

import { normalizeCountries, normalizeDisease } from "./normalizers";

const fallbackCountriesRaw: RestCountryRecord[] = [
  {
    name: { common: "United States", official: "United States of America" },
    cca2: "US",
    cca3: "USA",
    ccn3: "840",
    population: 334_805_269,
    area: 9_833_517,
    borders: ["CAN", "MEX"],
    flags: { svg: "https://flagcdn.com/us.svg" },
    latlng: [38, -97],
    region: "Americas",
  },
  {
    name: { common: "India", official: "Republic of India" },
    cca2: "IN",
    cca3: "IND",
    ccn3: "356",
    population: 1_400_000_000,
    area: 3_287_263,
    borders: ["PAK", "CHN", "NPL", "BGD", "BTN", "MMR"],
    flags: { svg: "https://flagcdn.com/in.svg" },
    latlng: [20, 77],
    region: "Asia",
  },
  {
    name: { common: "China", official: "People's Republic of China" },
    cca2: "CN",
    cca3: "CHN",
    ccn3: "156",
    population: 1_412_600_000,
    area: 9_706_961,
    borders: ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "NPL", "PAK", "RUS", "TJK", "VNM"],
    flags: { svg: "https://flagcdn.com/cn.svg" },
    latlng: [35, 105],
    region: "Asia",
  },
  {
    name: { common: "Brazil", official: "Federative Republic of Brazil" },
    cca2: "BR",
    cca3: "BRA",
    ccn3: "076",
    population: 214_326_223,
    area: 8_515_767,
    borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
    flags: { svg: "https://flagcdn.com/br.svg" },
    latlng: [-10, -55],
    region: "Americas",
  },
  {
    name: { common: "Russia", official: "Russian Federation" },
    cca2: "RU",
    cca3: "RUS",
    ccn3: "643",
    population: 144_100_000,
    area: 17_098_242,
    borders: ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
    flags: { svg: "https://flagcdn.com/ru.svg" },
    latlng: [60, 100],
    region: "Europe",
  },
  {
    name: { common: "Nigeria", official: "Federal Republic of Nigeria" },
    cca2: "NG",
    cca3: "NGA",
    ccn3: "566",
    population: 213_401_323,
    area: 923_768,
    borders: ["BEN", "CMR", "TCD", "NER"],
    flags: { svg: "https://flagcdn.com/ng.svg" },
    latlng: [10, 8],
    region: "Africa",
  },
  {
    name: { common: "France", official: "French Republic" },
    cca2: "FR",
    cca3: "FRA",
    ccn3: "250",
    population: 67_749_632,
    area: 551_695,
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
    flags: { svg: "https://flagcdn.com/fr.svg" },
    latlng: [46, 2],
    region: "Europe",
  },
  {
    name: { common: "Australia", official: "Commonwealth of Australia" },
    cca2: "AU",
    cca3: "AUS",
    ccn3: "036",
    population: 25_890_773,
    area: 7_692_024,
    borders: [],
    flags: { svg: "https://flagcdn.com/au.svg" },
    latlng: [-27, 133],
    region: "Oceania",
  },
  {
    name: { common: "South Africa", official: "Republic of South Africa" },
    cca2: "ZA",
    cca3: "ZAF",
    ccn3: "710",
    population: 59_392_255,
    area: 1_221_037,
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
    flags: { svg: "https://flagcdn.com/za.svg" },
    latlng: [-29, 24],
    region: "Africa",
  },
];

export const fallbackCountries = normalizeCountries(fallbackCountriesRaw);

export const fallbackDisease = normalizeDisease([
  { country: "United States", active: 786_167, cases: 111_820_082, deaths: 1_219_487, recovered: 109_814_428, countryInfo: { iso2: "US", iso3: "USA", lat: 38, long: -97 } },
  { country: "India", active: 4_891, cases: 45_000_000, deaths: 533_000, recovered: 44_460_000, countryInfo: { iso2: "IN", iso3: "IND", lat: 20, long: 77 } },
  { country: "China", active: 118_977, cases: 99_370_000, deaths: 121_878, recovered: 99_130_000, countryInfo: { iso2: "CN", iso3: "CHN", lat: 35, long: 105 } },
  { country: "Brazil", active: 330_401, cases: 38_743_918, deaths: 711_380, recovered: 37_702_137, countryInfo: { iso2: "BR", iso3: "BRA", lat: -10, long: -55 } },
  { country: "Russia", active: 171_231, cases: 24_124_215, deaths: 402_756, recovered: 23_550_228, countryInfo: { iso2: "RU", iso3: "RUS", lat: 60, long: 100 } },
  { country: "Nigeria", active: 3_101, cases: 267_188, deaths: 3_155, recovered: 260_932, countryInfo: { iso2: "NG", iso3: "NGA", lat: 10, long: 8 } },
]);

export const fallbackInterpol: InterpolAggregate = {
  counts: {
    USA: 9,
    IND: 14,
    CHN: 8,
    BRA: 11,
    RUS: 10,
    FRA: 7,
    NGA: 13,
    ZAF: 6,
  },
  notices: [
    { id: "fallback-interpol-1", name: "CLASSIFIED SUBJECT A", nationalities: ["IN"], charges: "Fraud and organized crime" },
    { id: "fallback-interpol-2", name: "CLASSIFIED SUBJECT B", nationalities: ["NG"], charges: "Cyber-enabled financial crime" },
    { id: "fallback-interpol-3", name: "CLASSIFIED SUBJECT C", nationalities: ["BR"], charges: "Drug trafficking" },
    { id: "fallback-interpol-4", name: "CLASSIFIED SUBJECT D", nationalities: ["US"], charges: "Violent crime" },
  ],
  total: 78,
  source: "fallback",
  fetchedAt: new Date().toISOString(),
  error: "Interpol upstream blocked this runtime; showing seeded aggregate fallback.",
};

export const fallbackCyber: CyberFeed = {
  counts: {
    USA: 4,
    FRA: 2,
    IND: 3,
    RUS: 2,
  },
  incidents: [
    {
      kind: "CYBER",
      id: "fallback-cyber-1",
      title: "Ransomware activity reported against healthcare systems",
      country: "United States",
      countryCode: "USA",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
    {
      kind: "CYBER",
      id: "fallback-cyber-2",
      title: "DDoS disruption reported against telecom infrastructure",
      country: "France",
      countryCode: "FRA",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
    {
      kind: "CYBER",
      id: "fallback-cyber-3",
      title: "Data breach coverage detected across regional outlets",
      country: "India",
      countryCode: "IND",
      source: "GDELT fallback",
      seenAt: new Date().toISOString(),
      url: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    },
  ],
  vulnerabilities: [
    {
      kind: "CISA KEV",
      id: "CVE-FALLBACK-1",
      cve: "CVE-FALLBACK-1",
      vendor: "Multiple vendors",
      product: "Internet-facing systems",
      name: "Known exploited vulnerability catalog fallback",
      dateAdded: new Date().toISOString().slice(0, 10),
      ransomware: "Unknown",
      action: "Review CISA KEV guidance and prioritize remediation.",
      url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
    },
  ],
  total: 11,
  source: "fallback",
  fetchedAt: new Date().toISOString(),
  cisaCatalogVersion: "fallback",
  error: "Cyber upstream unavailable; showing seeded incident fallback.",
};
